export const translations = {
  fr: {
    header: {
      title: "Assistant de Résumé Scientifique",
      desc: "Transformez vos articles scientifiques en résumés structurés et accessibles grâce à notre intelligence artificielle de pointe."
    },
    fileUpload: {
      title: "Déposez votre fichier PDF",
      subtitle: "ou cliquez pour sélectionner",
      languageLevel: "Niveau de langage :",
      simple: "Simple",
      standard: "Standard",
      technical: "Technique",
      summaryLength: "Longueur du résumé :",
      short: "Court",
      medium: "Moyen",
      detailed: "Détaillé",
      maxWords: "Nombre maximum de mots (optionnel) :",
      analyze: "Lancer l'analyse",
      preview: "Aperçu du document",
      config: "Configuration de l'analyse",
      language: "Langue"
    },
    voiceReader: {
      play: "Démarrer la lecture",
      pause: "Mettre en pause",
      resume: "Reprendre la lecture"
    },
    loader: {
      analyzing: "Analyse en cours",
      processing: "Traitement"
    },
    icon1: {
      title: "Rapide et Efficace",
      desc: "Obtenez des résumés pertinents en quelques secondes grâce à notre IA avancée."
    },
    icon2: {
      title: "Haute Précision",
      desc: "Des résumés fidèles qui capturent l'essence de vos articles scientifiques."
    },
    icon3: {
      title: "Format Structuré",
      desc: "Des résumés bien organisés pour une lecture et une compréhension optimales."
    },
    others: {
      res1: "Résumé Scientifique",
      res2: "Généré avec précision par IA",
      res3: "Résumé",
      copy: "Copier le résumé",
      download: "Télécharger en PDF",
      share: "Partager",
      copylink: "Copier le lien",
      lang: "fr"
    }
  },
  en: {
    header: {
      title: "Scientific Summary Assistant",
      desc: "Transform your scientific articles into structured and accessible summaries using our cutting-edge artificial intelligence."
    },
    fileUpload: {
      title: "Drop your PDF file",
      subtitle: "or click to select",
      languageLevel: "Language level:",
      simple: "Simple",
      standard: "Standard",
      technical: "Technical",
      summaryLength: "Summary length:",
      short: "Short",
      medium: "Medium",
      detailed: "Detailed",
      maxWords: "Maximum number of words (optional):",
      analyze: "Start analysis",
      preview: "Document preview",
      config: "Analysis configuration",
      language: "Language"
    },
    voiceReader: {
      play: "Start reading",
      pause: "Pause",
      resume: "Resume"
    },
    loader: {
      analyzing: "Analyzing",
      processing: "Processing"
    },
    icon1: {
      title: "Fast and Efficient",
      desc: "Get relevant summaries in seconds with our advanced AI."
    },
    icon2: {
      title: "High Accuracy",
      desc: "Accurate summaries that capture the essence of your scientific articles."
    },
    icon3: {
      title: "Structured Format",
      desc: "Well-organized summaries for optimal reading and comprehension."
    },
    others: {
      res1: "Scientific Summary",
      res2: "Accurately generated by AI",
      res3:"Summary",
      copy: "Copy the summary",
      download: "Download as PDF",
      share: "Share",
      copylink: "Copy the link",
      lang: "en"
    }
  }
}; 